# Generated by Django 2.2 on 2019-04-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstaPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_id', models.CharField(max_length=200, unique=True)),
                ('img', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
