# Generated by Django 2.2 on 2019-04-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uel', models.CharField(max_length=200, unique=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('description', models.TextField()),
            ],
        ),
    ]
