# Generated by Django 2.2 on 2019-04-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190423_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubpost',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='static/blog/img'),
        ),
    ]
