# Generated by Django 2.2 on 2019-04-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190423_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubpost',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='blog/static/blog/img'),
        ),
    ]
