# Generated by Django 2.2 on 2019-04-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190423_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubpost',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='github'),
        ),
    ]
